# Generated by Django 6.0.3 on 2026-04-21 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipamento',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Equipamento', 'verbose_name_plural': 'Equipamentos'},
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='peso',
        ),
        migrations.AddField(
            model_name='equipamento',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='data_fabricacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Fabricação'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Número de Série'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='predio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipamentos', to='core.predio', verbose_name='Prédio'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipamentos', to='core.departamento', verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='equipamentos/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipamentos', to='core.grupo', verbose_name='Grupo'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='local',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Local Específico'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='nome',
            field=models.CharField(max_length=150, verbose_name='Nome do Equipamento'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='numero_extintor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='ponto_referencia',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ponto de Referência'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/', verbose_name='QR Code'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='tipo_equipamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipamentos', to='core.tipoequipamento', verbose_name='Tipo de Equipamento'),
        ),
        migrations.CreateModel(
            name='Inspecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_inspecao', models.CharField(max_length=200, verbose_name='Nome da Inspeção')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('data_realizada', models.DateField(blank=True, null=True, verbose_name='Data da Realização')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('realizada', 'Realizada'), ('atrasada', 'Atrasada'), ('cancelada', 'Cancelada')], default='pendente', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspecoes', to='core.equipamento', verbose_name='Equipamento')),
                ('periodicidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspecoes', to='core.periodicidade', verbose_name='Periodicidade')),
            ],
            options={
                'verbose_name': 'Inspeção',
                'verbose_name_plural': 'Inspeções',
                'ordering': ['data_vencimento'],
            },
        ),
    ]
