# Generated by Django 6.0.3 on 2026-04-22 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_equipamento_options_remove_equipamento_peso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecaoChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ordem', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Seção do Checklist',
                'verbose_name_plural': 'Seções do Checklist',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='tipoequipamento',
            name='periodicidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipos_equipamento', to='core.periodicidade'),
        ),
        migrations.CreateModel(
            name='ItemChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=500)),
                ('tipo_resposta', models.CharField(choices=[('sim_nao', 'Sim/Não'), ('texto', 'Texto'), ('numero', 'Número'), ('data', 'Data'), ('foto', 'Foto')], default='sim_nao', max_length=20)),
                ('ordem', models.IntegerField(default=0)),
                ('obrigatorio', models.BooleanField(default=True)),
                ('detalhamento', models.TextField(blank=True, help_text='Instruções para responder a pergunta', null=True)),
                ('imagem_descritiva', models.ImageField(blank=True, null=True, upload_to='checklist/')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo_equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_checklist', to='core.tipoequipamento')),
                ('secao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens', to='core.secaochecklist')),
            ],
            options={
                'verbose_name': 'Item do Checklist',
                'verbose_name_plural': 'Itens do Checklist',
                'ordering': ['secao__ordem', 'ordem'],
            },
        ),
    ]
