# Generated by Django 6.0.3 on 2026-04-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_secaochecklist_tipoequipamento_periodicidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodicidade',
            name='tipo',
            field=models.CharField(blank=True, choices=[('dias', 'Dias'), ('semanas', 'Semanas'), ('meses', 'Meses'), ('anos', 'Anos')], max_length=10, null=True),
        ),
    ]
