# Generated by Django 6.0.3 on 2026-04-26 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_periodicidade_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='secaochecklist',
            name='tipo_equipamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secoes_checklist', to='core.tipoequipamento'),
        ),
        migrations.CreateModel(
            name='ServicoTipoEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obrigatorio', models.BooleanField(default=True)),
                ('vencimento_final_mes', models.BooleanField(default=False)),
                ('habilitar_assinatura', models.BooleanField(default=False)),
                ('assinatura_obrigatoria', models.BooleanField(default=False)),
                ('acoes_obrigatorias', models.BooleanField(default=False)),
                ('permitir_servicos_massa', models.BooleanField(default=False)),
                ('ordem', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('periodicidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicos_configurados', to='core.periodicidade')),
                ('tipo_equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos_configurados', to='core.tipoequipamento')),
                ('tipo_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamentos_configurados', to='core.tiposervico')),
            ],
            options={
                'verbose_name': 'Serviço do Tipo de Equipamento',
                'verbose_name_plural': 'Serviços do Tipo de Equipamento',
                'ordering': ['ordem', 'tipo_servico__nome'],
                'unique_together': {('tipo_equipamento', 'tipo_servico')},
            },
        ),
    ]
