# Generated by Django 6.0.3 on 2026-04-26 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_secaochecklist_tipo_equipamento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_realizacao', models.DateTimeField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='rascunho', max_length=20)),
                ('pontuacao_total', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('pontuacao_maxima', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='core.equipamento')),
                ('realizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicos_realizados', to=settings.AUTH_USER_MODEL)),
                ('tipo_servico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicos', to='core.tiposervico')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='RespostaChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcao', models.CharField(blank=True, choices=[('atende', 'Atende'), ('nao_atende', 'Não atende'), ('nao_aplica', 'Não se aplica')], max_length=20, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('fotos', models.ImageField(blank=True, null=True, upload_to='servicos/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('item_checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='core.itemchecklist')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='core.servico')),
            ],
            options={
                'verbose_name': 'Resposta do Checklist',
                'verbose_name_plural': 'Respostas do Checklist',
            },
        ),
        migrations.CreateModel(
            name='AcaoCorretiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problema', models.TextField()),
                ('acao', models.TextField()),
                ('responsaveis', models.CharField(help_text='Nomes dos responsáveis', max_length=500)),
                ('prazo', models.DateField()),
                ('anexos', models.FileField(blank=True, null=True, upload_to='acoes_servicos/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('item_checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoes', to='core.itemchecklist')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoes_corretivas', to='core.servico')),
            ],
            options={
                'verbose_name': 'Ação Corretiva',
                'verbose_name_plural': 'Ações Corretivas',
            },
        ),
    ]
