# Generated by Django 6.0.3 on 2026-04-26 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_servico_respostachecklist_acaocorretiva'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='servicotipoequipamento',
            unique_together={('tipo_equipamento', 'tipo_servico', 'periodicidade')},
        ),
        migrations.RemoveField(
            model_name='itemchecklist',
            name='tipo_equipamento',
        ),
        migrations.RemoveField(
            model_name='secaochecklist',
            name='tipo_equipamento',
        ),
        migrations.AddField(
            model_name='secaochecklist',
            name='servico_tipo_equipamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secoes_checklist', to='core.servicotipoequipamento'),
        ),
        migrations.AlterField(
            model_name='itemchecklist',
            name='secao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.secaochecklist'),
        ),
    ]
