# Generated by Django 6.0.3 on 2026-04-26 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_servicotipoequipamento_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemchecklist',
            name='secao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.secaochecklist'),
        ),
    ]
