# Generated by Django 6.0.3 on 2026-04-29 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_itemchecklist_secao'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioperfil',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/'),
        ),
        migrations.AddField(
            model_name='usuarioperfil',
            name='predio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='core.predio'),
        ),
    ]
