# Generated by Django 6.0.3 on 2026-06-08 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_relatoriogerado_equipamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160, unique=True)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('documento', models.CharField(blank=True, max_length=40, null=True)),
                ('dominio', models.CharField(blank=True, max_length=120, null=True)),
                ('ativa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='EmpresaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_acesso', models.CharField(choices=[('admin', 'Administrador'), ('analista', 'Analista'), ('usuario', 'Usuário'), ('convidado', 'Convidado')], default='usuario', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Usuário da Empresa',
                'verbose_name_plural': 'Usuários das Empresas',
                'ordering': ['empresa__nome', 'user__username'],
            },
        ),
        migrations.AlterField(
            model_name='departamento',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Série'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='periodicidade',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='predio',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tipoequipamento',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tiposervico',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='acaocorretiva',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_registros', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_registros', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_registros', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_registros', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='inspecao',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_registros', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='itemchecklist',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_registros', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='periodicidade',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_registros', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='predio',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_registros', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='relatoriogerado',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_registros', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='respostachecklist',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_registros', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='secaochecklist',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_registros', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='servico',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_registros', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='servicotipoequipamento',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_registros', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='tipoequipamento',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_registros', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='tiposervico',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_registros', to='core.empresa'),
        ),
        migrations.AddConstraint(
            model_name='departamento',
            constraint=models.UniqueConstraint(fields=('empresa', 'nome'), name='unique_departamento_empresa_nome'),
        ),
        migrations.AddConstraint(
            model_name='equipamento',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero_serie'), name='unique_equipamento_empresa_numero_serie'),
        ),
        migrations.AddConstraint(
            model_name='grupo',
            constraint=models.UniqueConstraint(fields=('empresa', 'nome'), name='unique_grupo_empresa_nome'),
        ),
        migrations.AddConstraint(
            model_name='periodicidade',
            constraint=models.UniqueConstraint(fields=('empresa', 'nome'), name='unique_periodicidade_empresa_nome'),
        ),
        migrations.AddConstraint(
            model_name='predio',
            constraint=models.UniqueConstraint(fields=('empresa', 'nome'), name='unique_predio_empresa_nome'),
        ),
        migrations.AddConstraint(
            model_name='tipoequipamento',
            constraint=models.UniqueConstraint(fields=('empresa', 'nome'), name='unique_tipo_equipamento_empresa_nome'),
        ),
        migrations.AddConstraint(
            model_name='tiposervico',
            constraint=models.UniqueConstraint(fields=('empresa', 'nome'), name='unique_tipo_servico_empresa_nome'),
        ),
        migrations.AddField(
            model_name='empresausuario',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='empresausuario',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='empresausuario',
            constraint=models.UniqueConstraint(fields=('empresa', 'user'), name='unique_empresa_usuario'),
        ),
    ]
