# Generated by Codex on 2026-06-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_notificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='possui_vencimento',
            field=models.BooleanField(default=False, verbose_name='Possui vencimento'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='data_vencimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de vencimento'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='vencimento_carga',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimento da carga'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='vencimento_teste_hidrostatico',
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name='Vencimento do teste hidrostático do casco',
            ),
        ),
    ]
