# Generated by Django 6.0.3 on 2026-06-30 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_equipamento_vencimentos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Aguardando tratativa'), ('resolvido', 'Resolvido')], default='pendente', max_length=20)),
                ('tratativa', models.TextField(blank=True, null=True)),
                ('resolvido_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_checklist_criados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_registros', to='core.empresa')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_checklist', to='core.equipamento')),
                ('resolvido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_checklist_resolvidos', to=settings.AUTH_USER_MODEL)),
                ('resposta_checklist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alerta_checklist', to='core.respostachecklist')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_checklist', to='core.servico')),
            ],
            options={
                'verbose_name': 'Alerta de Checklist',
                'verbose_name_plural': 'Alertas de Checklist',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['status', '-criado_em'], name='core_alerta_status_90cbef_idx'), models.Index(fields=['criado_por', 'status', '-criado_em'], name='core_alerta_criado__8c0073_idx')],
            },
        ),
    ]
