# Generated by Django 6.0.3 on 2026-06-30 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alertachecklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresausuario',
            name='tipo_acesso',
            field=models.CharField(choices=[('admin', 'Administrador'), ('supervisor', 'Supervisor'), ('analista', 'Analista'), ('usuario', 'Usuário'), ('convidado', 'Convidado')], default='usuario', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuarioperfil',
            name='tipo_acesso',
            field=models.CharField(choices=[('admin', 'Administrador'), ('supervisor', 'Supervisor'), ('analista', 'Analista'), ('usuario', 'Usuário'), ('convidado', 'Convidado')], default='usuario', max_length=20),
        ),
    ]
