# Generated by Codex on 2026-07-01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_empresausuario_tipo_acesso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatoriogerado',
            name='servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.servico'),
        ),
    ]
